name: Build and Deploy FFmpeg Azure Function

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ffmpegacr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        docker build -t ffmpegacr.azurecr.io/mp4converter:latest .
        docker push ffmpegacr.azurecr.io/mp4converter:latest

    - name: Deploy to Azure Web App for Containers
      uses: azure/webapps-deploy@v2
      with:
        app-name: mp4converter
        images: ffmpegacr.azurecr.io/mp4converter:latest